### ISSUE TITLE
[XMLSEC1] Errore durante verifica signature AuthnRequest

### ISSUE THREAD

**Issue by AlterEchoes** [italia/spid-sp-test#101]
Sto eseguendo la suite di test per la Request SAML e durante il check della validità della firma, ottengo questo errore:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/spid_sp_test/authn_request.py", line 384, in test_xmldsig
    out = subprocess.run(
  File "/usr/local/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'xmlsec1 --verify --insecure --id-attr:ID "urn:oasis:names:tc:SAML:2.0:protocol:AuthnRequest" --pubkey-pem /tmp/tmp7joe_1si.crt /tmp/tmpv4m5qztq.xml ' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/spid_sp_test", line 327, in <module>
    selective_run(authn_check, profile, args.list)
  File "/usr/local/bin/spid_sp_test", line 32, in selective_run
    method()
  File "/usr/local/lib/python3.8/site-packages/spid_sp_test/authn_request.py", line 1111, in test_profile_spid_sp
    self.test_xmldsig()
  File "/usr/local/lib/python3.8/site-packages/spid_sp_test/authn_request.py", line 415, in test_xmldsig
    self.handle_result(
KeyError: `'description'
```

e l'esecuzione si interrompe.
La versione utilizzata è la 0.9.14 su Windows

**Comment by peppelinux** [comment]
Grazie, risolto qui
https://github.com/italia/spid-sp-test/releases/tag/v0.9.16
