### ISSUE TITLE
Impossibile avviare spid-saml-check versione 1.9.2

### ISSUE THREAD

**Issue by pisanialfonso** [italia/spid-sp-test#152]
Buongiorno,
cercando di avviare la verisione 1.9.2 o la latest con il comando 

docker run -t -i -p 8443:8443 italia/spid-saml-check: v.1.9.2    oppure docker run -t -i -p 8443:8443 italia/spid-saml-check : latest
ottengo in ambo i casi un errore "Cannot find module 'express".
Qualcuno può aiutarmi per favore?

DI seguito le printout

Last login: Tue Sep 27 11:40:01 2022 from 172.16.128.185
congenius@ubuntu20spid:~$ sudo docker run -t -i -p 8443:8443 italia/spid-saml-ch                                               eck : v.1.9.2
[sudo] password for congenius:
Unable to find image 'italia/spid-saml-check:latest' locally
latest: Pulling from italia/spid-saml-check
1fe172e4850f: Pull complete
e668081a2733: Pull complete
a55e0b57fcd3: Pull complete
123f877d197e: Pull complete
cc38f6504a4f: Pull complete
6597b3f92bfa: Pull complete
0f796f194602: Pull complete
b44a46461e94: Pull complete
66fe3df788d0: Pull complete
39a5ee31bee0: Pull complete
e7347f3cb3ac: Pull complete
58d4b3f63611: Pull complete
d1965d221521: Pull complete
Digest: sha256:c6f184134391fdafde0ffe255eacebab08102c8f51f568c8b843d77c84f8e571
Status: Downloaded newer image for italia/spid-saml-check:latest

> [spid-validator@1.0.0](mailto:spid-validator@1.0.0) start-prod /spid-saml-check/spid-validator
> node server/spid-validator.js

internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'express'
Require stack:
- /spid-saml-check/spid-validator/server/spid-validator.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/spid-saml-check/spid-validator/server/spid-validator.js:2:17)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/spid-saml-check/spid-validator/server/spid-validator.js' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! [spid-validator@1.0.0](mailto:spid-validator@1.0.0) start-prod: `node server/spid-validator.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the [spid-validator@1.0.0](mailto:spid-validator@1.0.0) start-prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-09-28T13_23_26_618Z-debug.log
congenius@ubuntu20spid:~$

congenius@ubuntu20spid:~$ sudo docker run -t -i -p 8443:8443 italia/spid-saml-check : latest

> [spid-validator@1.0.0](mailto:spid-validator@1.0.0) start-prod /spid-saml-check/spid-validator
> node server/spid-validator.js

internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'express'
Require stack:
- /spid-saml-check/spid-validator/server/spid-validator.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/spid-saml-check/spid-validator/server/spid-validator.js:2:17)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/spid-saml-check/spid-validator/server/spid-validator.js' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! [spid-validator@1.0.0](mailto:spid-validator@1.0.0) start-prod: `node server/spid-validator.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the [spid-validator@1.0.0](mailto:spid-validator@1.0.0) start-prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-09-28T13_25_12_510Z-debug.log

**Comment by peppelinux** [comment]
Ciao questa issue è per spid-saml-check piuttosto che per spid-sp-test

https://github.com/italia/spid-saml-check
