### ISSUE TITLE
AssertionConsumerServiceURL required when using --html-path

### ISSUE THREAD

**Issue by mauromol** [italia/spid-sp-test#68]
When adding the `--html-path` command line argument to produce the HTML dumps of the captured landing pages, spid_sp_test crashes if the `AuthnRequest` does not use the pair `AssertionConsumerServiceURL`+`ProtocolBinding`, but rather `AssertionConsumerServiceIndex`, which however is the option "recommended" by the SPID specification.

Here is the exception:
```
Traceback (most recent call last): 
 File "/home/mauro/workspace/python-env/spid_sp_test/bin/spid_sp_test", line 7, in <module> 
   exec(compile(f.read(), __file__, 'exec')) 
 File "/home/mauro/git/spid-sp-test/src/spid_sp_test/spid_sp_test", line 323, in <module> 
   selective_run(response_check, profile, args.list) 
 File "/home/mauro/git/spid-sp-test/src/spid_sp_test/spid_sp_test", line 31, in selective_run 
   method() 
 File "/home/mauro/git/spid-sp-test/src/spid_sp_test/../spid_sp_test/response.py", line 359, in test_profile_spid_sp 
   self.dump_html_response( 
 File "/home/mauro/git/spid-sp-test/src/spid_sp_test/../spid_sp_test/response.py", line 295, in dump_html_response 
   url = self.authnreq_attrs["AssertionConsumerServiceURL"] 
 File "src/lxml/etree.pyx", line 2479, in lxml.etree._Attrib.__getitem__ 
KeyError: 'AssertionConsumerServiceURL'
```

**Comment by peppelinux** [comment]
Done here
https://github.com/italia/spid-sp-test/commit/c0bd40086b1d8769805ee3e51f78058e9a79615e
